In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
zip_county_fips = "zip_county_fips.csv"
zip_county_fips_df = pd.read_csv(zip_county_fips)
zip_county_fips_df.head(15)

      ZIP  STCOUNTYFP           CITY STATE      COUNTYNAME CLASSFP
0   36091        1001        Verbena    AL  Autauga County      H1
1   36758        1001  Plantersville    AL  Autauga County      H1
2   36006        1001    Billingsley    AL  Autauga County      H1
3   36067        1001     Prattville    AL  Autauga County      H1
4   36701        1001          Selma    AL  Autauga County      H1
5   36003        1001   Autaugaville    AL  Autauga County      H1
6   36008        1001          Booth    AL  Autauga County      H1
7   36068        1001     Prattville    AL  Autauga County      H1
8   36022        1001     Deatsville    AL  Autauga County      H1
9   36703        1001          Selma    AL  Autauga County      H1
10  36749        1001          Jones    AL  Autauga County      H1
11  36066        1001     Prattville    AL  Autauga County      H1
12  36051        1001        Marbury    AL  Autauga County      H1
13  36502        1003         Atmore    AL  Baldwin County      H1
14  36507        1003    Bay minette    AL  Baldwin County      H1

In [13]:
clean_county = zip_county_fips_df.COUNTYNAME.map(lambda x: x.replace(" County", ""))
zip_county_fips_df.COUNTYNAME = clean_county
zip_county_fips_df

         ZIP  STCOUNTYFP           CITY STATE         COUNTYNAME CLASSFP
0      36091        1001        Verbena    AL            Autauga      H1
1      36758        1001  Plantersville    AL            Autauga      H1
2      36006        1001    Billingsley    AL            Autauga      H1
3      36067        1001     Prattville    AL            Autauga      H1
4      36701        1001          Selma    AL            Autauga      H1
...      ...         ...            ...   ...                ...     ...
53957    820       78010  Christiansted    VI   St. Croix Island      H4
53958    840       78010   Frederiksted    VI   St. Croix Island      H4
53959    850       78010      Kingshill    VI   St. Croix Island      H4
53960    830       78020        St john    VI    St. John Island      H4
53961    802       78030      St thomas    VI  St. Thomas Island      H4

[53962 rows x 6 columns]

In [15]:
# drop all states that are not california
cleaned_df = zip_county_fips_df.loc[zip_county_fips_df["STATE"] == "CA", :]
cleaned_df

        ZIP  STCOUNTYFP            CITY STATE COUNTYNAME CLASSFP
2904  94501        6001         Alameda    CA    Alameda      H1
2905  94560        6001          Newark    CA    Alameda      H1
2906  94577        6001     San leandro    CA    Alameda      H1
2907  94578        6001     San leandro    CA    Alameda      H1
2908  94550        6001       Livermore    CA    Alameda      H1
...     ...         ...             ...   ...        ...     ...
5544  95941        6115      Forbestown    CA       Yuba      H1
5545  95960        6115  North san juan    CA       Yuba      H1
5546  95919        6115     Brownsville    CA       Yuba      H1
5547  95966        6115        Oroville    CA       Yuba      H1
5548  95918        6115   Browns valley    CA       Yuba      H1

[2645 rows x 6 columns]