In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
# US county file

us_county_file = "../us_county.csv"
us_county_df = pd.read_csv(us_county_file)
us_county_df.head(15)

,fips,county,state,state_code,male,female,median_age,population,female_percentage,lat,long
0,1001,Autauga County,Alabama,AL,26874,28326,37.8,55200,51.315217,32.534923,-86.642730
1,1003,Baldwin County,Alabama,AL,101188,106919,42.8,208107,51.376936,30.727479,-87.722564
2,1005,Barbour County,Alabama,AL,13697,12085,39.9,25782,46.873788,31.869581,-85.393210
3,1007,Bibb County,Alabama,AL,12152,10375,39.9,22527,46.055844,32.998628,-87.126475
4,1009,Blount County,Alabama,AL,28434,29211,40.8,57645,50.673953,33.980869,-86.567380
5,1011,Bullock County,Alabama,AL,5663,4689,39.6,10352,45.295595,32.100525,-85.715679
6,1013,Butler County,Alabama,AL,9368,10657,40.7,20025,53.218477,31.752429,-86.680276
7,1015,Calhoun County,Alabama,AL,55315,59783,39.7,115098,51.940955,33.771416,-85.826039
8,1017,Chambers County,Alabama,AL,16257,17569,43.0,33826,51.939337,32.914345,-85.392030
9,1019,Cherokee County,Alabama,AL,12820,13033,45.9,25853,50.411944,34.175905,-85.603801
10,1021,Chilton County,Alabama,AL,21672,22258,38.6,43930,50.666970,32.847867,-86.718790
11,1023,Choctaw County,Alabama,AL,6253,6822,46.1,13075,52.175908,32.019772,-88.263180
12,1025,Clarke County,Alabama,AL,11539,12848,42.3,24387,52.683807,31.676678,-87.830809
13,1027,Clay County,Alabama,AL,6464,6914,43.7,13378,51.681866,33.269024,-85.860579
14,1029,Cleburne County,Alabama,AL,7281,7657,42.5,14938,51.258535,33.674513,-85.518809

In [5]:
# US county covid file

covid_us_county_file = "../covid_us_county.csv"
covid_us_county_df = pd.read_csv(covid_us_county_file)
covid_us_county_df.head(15)

,fips,county,state,lat,long,date,cases,state_code,deaths
0,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-22,0,AL,0
1,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-23,0,AL,0
2,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-24,0,AL,0
3,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-25,0,AL,0
4,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-26,0,AL,0
5,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-27,0,AL,0
6,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-28,0,AL,0
7,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-29,0,AL,0
8,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-30,0,AL,0
9,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-01-31,0,AL,0
10,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-02-01,0,AL,0
11,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-02-02,0,AL,0
12,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-02-03,0,AL,0
13,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-02-04,0,AL,0
14,1001.0,Autauga,Alabama,32.539527,-86.644082,2020-02-05,0,AL,0

In [6]:
# PPP loan file

ppp_loan_ca_file = "../PPP_loan_CA.csv"
ppp_loan_ca_df = pd.read_csv(ppp_loan_ca_file)
ppp_loan_ca_df.head(15)

,BusinessName,Address,City,State,Zip,NAICSCode,BusinessType,JobsRetained,DateApproved,Lender
0,"220 LABORATORIES, INC.",2375 Third Street,RIVERSIDE,CA,92507,325620.0,Subchapter S Corporation,500.0,4/27/2020,Riverview Bank
1,A-C ELECTRIC COMPANY,2921 HANGER WAY,BAKERSFIELD,CA,93308,238210.0,Corporation,341.0,4/9/2020,Mission Bank
2,A.O. REED & CO,4777 RUFFNER ST,SAN DIEGO,CA,92111,238220.0,Corporation,477.0,4/14/2020,Umpqua Bank
3,"AARON THOMAS COMPANY, INC",7421 CHAPMAN AVANUE,GARDEN GROVE,CA,92841,561910.0,Subchapter S Corporation,500.0,4/28/2020,"U.S. Bank, National Association"
4,"ACCURATE BACKGROUND, LLC",7515 Irvine Center Drive,IRVINE,CA,92618,561611.0,Limited Liability Company(LLC),500.0,4/11/2020,"Zions Bank, A Division of"
5,"ADVANCED CHEMICAL TRANSPORT, INC., A CALIFORNI...",967 MABURY RD,SAN JOSE,CA,95133,562910.0,Subchapter S Corporation,407.0,4/10/2020,Comerica Bank
6,ADVANCED FRESH CONCEPTS FRANCHISE CORP.,19205 South Laurel Park Road,RANCHO DOMINGUEZ,CA,90220,722513.0,Sole Proprietorship,420.0,4/27/2020,"MUFG Union Bank, National Association"
7,ADVANCED SYSTEMS GROUP,1226 Powell St.,EMERYVILLE,CA,94608,423410.0,Limited Liability Company(LLC),300.0,4/30/2020,Cache Valley Bank
8,ADVANTAGE MAILING INC.,1600 N KRAEMER BLVD,ANAHEIM,CA,92806,323111.0,Limited Liability Company(LLC),372.0,4/27/2020,Cathay Bank
9,"AGREEYA SOLUTIONS, INC.","605 Coolidge Dr., STE 200",FOLSOM,CA,95630,541511.0,Subchapter S Corporation,397.0,4/16/2020,Bank of the West
10,AIR SYSTEMS OF SACRAMENTO INC,10381 OLD PLACERVILLE RD,SACRAMENTO,CA,95827,238220.0,Corporation,203.0,4/9/2020,Merchants Bank of Commerce
11,"AIRPORT TERMINAL MANAGEMENT, INC.",216 W. FLORENCE AVE,INGLEWOOD,CA,90301,488190.0,Corporation,450.0,4/15/2020,Commercial Bank of California
12,"AKASH MANAGEMENT, LLC",716 CORPORATE CENTER DR,POMONA,CA,91768,722513.0,Limited Liability Company(LLC),500.0,4/5/2020,City National Bank
13,ALATUS AEROSYSTEMS,17055 GALE AVE,CITY OF INDUSTRY,CA,91745,336413.0,Corporation,333.0,4/12/2020,"INTRUST Bank, National Association"
14,ALIA CORP,140 Heron Way 0.0,MERCED,CA,95341,722513.0,Corporation,500.0,4/11/2020,"JPMorgan Chase Bank, National Association"